### ISSUE TITLE
Its working also for Mi Band 3?

### ISSUE THREAD

**Issue by matanel12345** [kshtj24/mi-band-2-connect#4]
variableService = bluetoothGatt.getService(UUIDs.HEART_RATE_SERVICE);
BluetoothGattCharacteristic heartRateCharacteristic = variableService.getCharacteristic(UUIDs.HEART_RATE_MEASUREMENT_CHARACTERISTIC);

i get:
java.lang.NullPointerException: Attempt to invoke virtual method 'android.bluetooth.BluetoothGattCharacteristic android.bluetooth.BluetoothGattService.getCharacteristic(java.util.UUID)' on a null object reference

10x for help

**Comment by kshtj24** [comment]
Haven't checked for Mi Band 3.
